// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportGen.Data;

#nullable disable

namespace ReportGen.Data.Migrations
{
    [DbContext(typeof(ReportGenDbContext))]
    [Migration("20250717113601_AddGetFunction")]
    partial class AddGetFunction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportGen.Models.Result", b =>
                {
                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("AvgExecutionTime")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AvgStoreValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DeltaTimeS")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaximumStoreValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MedianStoreValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("MinimumDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinimumStoreValue")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("FileName");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("ReportGen.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExecutionTimeS")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StoreValue")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("ReportGen.Models.Value", b =>
                {
                    b.HasOne("ReportGen.Models.Result", "Result")
                        .WithMany("Values")
                        .HasForeignKey("FileName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("ReportGen.Models.Result", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
